#!/bin/bash

set -e  # Exit on error

echo "🚀 DeLong Protocol v1 - Full Deployment & Configuration Update"
echo "=============================================================="
echo ""

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Load environment variables
if [ ! -f .env ]; then
    echo "❌ Error: .env file not found"
    exit 1
fi
source .env

# Project paths
CONTRACT_DIR="$(pwd)"
DLEX_DIR="${CONTRACT_DIR}/../dlex"
DLEX_BACKEND_DIR="${CONTRACT_DIR}/../dlex-backend"
SUBGRAPH_DIR="${CONTRACT_DIR}/../subgraph"

# =============================================================================
# Step 1: Deploy Contracts to Sepolia
# =============================================================================
echo "📦 Step 1: Deploying contracts to Sepolia..."
echo ""

# Deploy without verification (too slow)
forge script script/DeploySepolia.s.sol:DeploySepolia \
    --rpc-url $SEPOLIA_RPC_URL \
    --broadcast \
    --skip-simulation \
    -vv

if [ $? -ne 0 ]; then
    echo -e "${RED}❌ Contract deployment failed${NC}"
    exit 1
fi

echo -e "${GREEN}✅ Contracts deployed successfully${NC}"
echo ""

# =============================================================================
# Step 2: Load deployed addresses
# =============================================================================
echo "📋 Step 2: Loading deployed addresses..."

if [ ! -f "./deployments/sepolia.env" ]; then
    echo -e "${RED}❌ Error: deployments/sepolia.env not found${NC}"
    exit 1
fi

source ./deployments/sepolia.env

echo "Loaded addresses:"
echo "  Factory: $FACTORY_ADDRESS"
echo "  RentalManager: $RENTAL_MANAGER_ADDRESS"
echo "  DAOTreasury: $DAO_TREASURY_ADDRESS"
echo "  DAOGovernance: $DAO_GOVERNANCE_ADDRESS"
echo ""

# =============================================================================
# Step 3: Update Subgraph Configuration
# =============================================================================
echo "🔄 Step 3: Updating subgraph configuration..."

if [ -d "$SUBGRAPH_DIR" ]; then
    cd "$SUBGRAPH_DIR"

    # Backup original subgraph.yaml
    if [ -f "subgraph.yaml" ]; then
        cp subgraph.yaml subgraph.yaml.backup
    fi

    # Update subgraph.yaml with new addresses
    # Note: This uses awk to update the addresses in place
    awk -v factory="$FACTORY_ADDRESS" -v rental="$RENTAL_MANAGER_ADDRESS" '
        /address:/ && /Factory/ { gsub(/"[^"]*"/, "\"" tolower(factory) "\""); print; next }
        /address:/ && /RentalManager/ { gsub(/"[^"]*"/, "\"" tolower(rental) "\""); print; next }
        { print }
    ' subgraph.yaml > subgraph.yaml.tmp && mv subgraph.yaml.tmp subgraph.yaml

    echo -e "${GREEN}✅ Subgraph configuration updated${NC}"

    # Regenerate subgraph code
    echo "🔨 Generating subgraph code..."
    pnpm run codegen

    # Deploy subgraph
    echo "📡 Deploying subgraph..."
    pnpm run deploy

    if [ $? -ne 0 ]; then
        echo -e "${YELLOW}⚠️  Subgraph deployment failed, but continuing...${NC}"
    else
        echo -e "${GREEN}✅ Subgraph deployed${NC}"
    fi

    cd "$CONTRACT_DIR"
else
    echo -e "${YELLOW}⚠️  Subgraph directory not found, skipping...${NC}"
fi

echo ""

# =============================================================================
# Step 4: Update Frontend Environment Variables
# =============================================================================
echo "🎨 Step 4: Updating frontend environment variables..."

if [ -d "$DLEX_DIR" ]; then
    ENV_FILE="$DLEX_DIR/.env.local"

    # Backup existing .env.local
    if [ -f "$ENV_FILE" ]; then
        cp "$ENV_FILE" "$ENV_FILE.backup"
    fi

    # Update or create .env.local
    cat > "$ENV_FILE" << EOF
# Auto-generated by deploy-and-update.sh
# Generated at: $(date)

# Contract Addresses (Sepolia)
NEXT_PUBLIC_FACTORY_ADDRESS=$FACTORY_ADDRESS
NEXT_PUBLIC_RENTAL_MANAGER_ADDRESS=$RENTAL_MANAGER_ADDRESS
NEXT_PUBLIC_DAO_TREASURY_ADDRESS=$DAO_TREASURY_ADDRESS
NEXT_PUBLIC_DAO_GOVERNANCE_ADDRESS=$DAO_GOVERNANCE_ADDRESS
NEXT_PUBLIC_USDC_ADDRESS=$USDC_ADDRESS

# Network
NEXT_PUBLIC_CHAIN_ID=11155111
NEXT_PUBLIC_RPC_URL=$SEPOLIA_RPC_URL

# Subgraph API (update this after subgraph deployment)
NEXT_PUBLIC_SUBGRAPH_URL=https://api.studio.thegraph.com/query/YOUR_SUBGRAPH_ID/delong-protocol/version/latest
EOF

    echo -e "${GREEN}✅ Frontend .env.local updated${NC}"
else
    echo -e "${YELLOW}⚠️  Frontend directory not found, skipping...${NC}"
fi

echo ""

# =============================================================================
# Summary
# =============================================================================
echo "=============================================================="
echo -e "${GREEN}✅ Deployment and configuration update complete!${NC}"
echo "=============================================================="
echo ""
echo "📊 Summary:"
echo "  ✅ Contracts deployed to Sepolia"
echo "  ✅ Subgraph configuration updated"
echo "  ✅ Frontend .env.local updated"
echo ""
echo "🔗 Deployed Addresses:"
echo "  Factory:       $FACTORY_ADDRESS"
echo "  RentalManager: $RENTAL_MANAGER_ADDRESS"
echo "  DAOTreasury:   $DAO_TREASURY_ADDRESS"
echo "  DAOGovernance: $DAO_GOVERNANCE_ADDRESS"
echo ""
echo "📝 Next Steps:"
echo "  1. Update NEXT_PUBLIC_SUBGRAPH_URL in frontend .env.local"
echo "  2. Update backend environment variables if needed"
echo "  3. Test frontend and backend connections"
echo ""
